# Generated by Django 4.0.2 on 2023-06-03 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_creator', '0003_remove_usercharacterattributes_acrobatics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentSessionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=1024)),
                ('whichSession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='character_creator.gamesession')),
            ],
        ),
    ]
